backend:
  name: github
  repo: martinseanhunt/mh-codes
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/content/pages/home.md'
        label: 'Home Page'
        name: 'home'
        media_folder: ''
        public_folder: ''
        editor:
          preview: false
        fields:
          - { label: 'HTML Title Suffix', name: 'htmlTitle', widget: 'string' }
          - { label: 'Headline', name: 'heading', widget: 'string' }
          - { label: 'Bio', name: 'bio', widget: 'markdown' }
          - { label: 'FullBio', name: 'body', widget: 'markdown' }
          - {
              label: 'History Section Title',
              name: 'historyTitle',
              widget: 'string',
            }
          - { label: 'Blog Section Title', name: 'blogTitle', widget: 'string' }
      - file: 'src/content/pages/projects.md'
        label: 'Projects'
        name: 'projects'
        media_folder: ''
        public_folder: ''
        editor:
          preview: false
        fields:
          - { label: 'HTML Title Suffix', name: 'htmlTitle', widget: 'string' }
          - { label: 'Headline', name: 'heading', widget: 'string' }
          - { label: 'Intro Text', name: 'intro', widget: 'markdown' }
      - file: 'src/content/pages/blog.md'
        label: 'Blog'
        name: 'blog'
        media_folder: ''
        public_folder: ''
        editor:
          preview: false
        fields:
          - { label: 'HTML Title Suffix', name: 'htmlTitle', widget: 'string' }
          - { label: 'Headline', name: 'heading', widget: 'string' }
          - { label: 'Intro Text', name: 'intro', widget: 'markdown' }
      - file: 'src/content/pages/bio.md'
        label: 'Bio'
        name: 'bio'
        media_folder: ''
        public_folder: ''
        editor:
          preview: false
        fields:
          - { label: 'HTML Title Suffix', name: 'htmlTitle', widget: 'string' }
          - { label: 'Headline', name: 'heading', widget: 'string' }
          - { label: 'Intro Text', name: 'intro', widget: 'markdown' }
          - { label: 'Bio', name: 'body', widget: 'markdown' }

  - name: 'blog'
    label: 'Blog'
    folder: 'src/content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - {
          label: 'External Post URL',
          name: 'externalUrl',
          widget: 'string',
          required: false,
          hint: 'Leave blank for an internal post',
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          allow_multiple: false,
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Linked Post',
          name: 'linkedPost',
          widget: 'string',
          required: false,
        }

  - name: 'history'
    label: 'History'
    folder: 'src/content/history'
    create: true
    slug: 'index'
    path: '{{company}}/index'
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'history-item',
        }
      - { label: 'Company', name: 'company', widget: 'string' }
      - {
          label: 'Order',
          name: 'order',
          widget: 'number',
          required: false,
          value_type: 'int',
          hint: 'Leave blank for auto ordering',
        }
      - { label: 'Role', name: 'role', widget: 'string' }
      - { label: 'From - To', name: 'dates', widget: 'string' }
      - {
          label: 'Excerpt',
          name: 'excerpt',
          widget: 'text',
          hint: 'auto generated if blank',
          required: false,
        }
      - {
          label: 'Key Acheivements',
          name: 'acheivements',
          widget: 'list',
          required: false,
          field: { label: Acheivement, name: 'acheivement', widget: 'string' },
        }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          allow_multiple: false,
          required: false,
        }
      - {
          label: 'Testimonial',
          name: 'testimonial',
          widget: 'text',
          required: false,
        }
      - {
          label: 'Testimonial Author',
          name: 'testimonialAuthor',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Testimonial Avatar',
          name: 'testimonialAvatar',
          widget: 'image',
          allow_multiple: false,
          required: false,
        }
      - {
          label: 'Link To Details Page',
          name: 'linkToDetails',
          widget: 'boolean',
          default: false,
          hint: 'If false, the history item will not link through to a details page',
        }
      - {
          label: 'External Url',
          name: 'externalUrl',
          widget: 'string',
          required: false,
          hint: 'The company website',
        }

  - name: 'project'
    label: 'Project'
    folder: 'src/content/projects'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'project',
        }
      - { label: 'Title', name: 'title', widget: 'string', required: false }
      - {
          label: 'Order',
          name: 'order',
          widget: 'number',
          required: false,
          value_type: 'int',
          hint: 'Leave blank for auto ordering',
        }
      - {
          label: 'Excerpt',
          name: 'excerpt',
          widget: 'text',
          hint: 'auto generated if blank',
          required: false,
        }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Featured Logo',
          name: 'logo',
          widget: 'image',
          required: false,
          allow_multiple: false,
        }
      - {
          label: 'Github Url',
          name: 'github',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Live Url',
          name: 'liveUrl',
          widget: 'string',
          required: false,
          default: null,
        }
      - {
          label: 'Link To Details Page',
          name: 'linkToDetails',
          widget: 'boolean',
          default: false,
          hint: 'If false, the history item will not link through to a details page',
        }
